name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: configure
      run: cmake .. ; python -m pip install cffi

    - name: build
      run: make ; du -a

    - name: build backend
      run: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:./build/sample:./build/extended; python main_builder.py; python extend_build.py

    - name: Run Tests
      run: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:./build/sample:./build/extended; python test.py; python e_test.py
