name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: configure
      run: mkdir build; cd build && cmake .. ; python -m pip install cffi

    - name: build
      run: cd build && make ; du -a

    - name: build backend
      run: python main_builder.py ; python extend_build.py

    - name: Run distcheck
      run: du; python test.py ; python e_test.py
